massanger:
  join: '&aДобро пожаловать на сервер!'
  notperms: '&cУ вас недостаточно прав.'
  changeworld: '&eВы в мире:'
  teleport: '&eВы телепортированы на кординаты'
  respawn: '&aДобро пожаловать, заново в этом мир!'